name: Receive-inputs

on: [ workflow_dispatch ]

jobs:
  deploy:
    name: Print Inputs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Input mario: ${{ github.event.inputs.mario }}" 
    
