name: Receive-inputs

on: 
  workflow_dispatch:
    inputs:
      mario:
        description: 'mario'     
        required: true

jobs:
  deploy:
    name: Print Inputs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Input mario: ${{ github.event.inputs.mario }}" 
    
