name: Receive-inputs

on: 
  workflow_dispatch:
    inputs:
      mario:
        description: 'mario'     
        required: true
      sha:
        descrption: 'sha'
        required: true
      sha1:
        descrption: 'sha1'
        required: true

jobs:
  deploy:
    name: Print Inputs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Input mario: ${{ github.event.inputs.mario }}" 
          echo "Input sha: ${{ github.event.inputs.sha }}"
          echo "Input sha: ${{ github.event.inputs.sha1 }}" 
    
